language: objective-c
osx_image: xcode8
env:
  matrix:
  - ACTION=build-framework
  - ACTION=build-example
cache:
  bundler: true
  directories:
  - vendor/bundle
  - Pods
before_install:
  - export LANG=en_US.UTF-8
  - brew tap homebrew/bundle
  - brew bundle
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install --no-repo-update
script:
  - make $ACTION
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make coverage
notifications:
  email: false
